language: python
python:
  "2.7"
os:
  - linux
notifications:
  email: false
sudo: required
dist: xenial
services:
  - xvfb
#addons:
#  apt:
#    packages:
#      - mesa-utils
install:
  - sudo apt-get mesa-utils
before_script:
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render;
  - sleep 3 
script:
  - glxinfo
  - timeout 5 glxgears || true
