language: python
python:
  "2.7"
os:
  - linux
notifications:
  email: false
sudo: required
dist: trusty
services:
  - xvfb
addons:
  apt:
     packages:
        - libglew-dev
        - freeglut3-dev
        - libxi-dev
        - libxmu-dev
        - xserver-xorg-video-dummy
        - xpra
        - xorg-dev
        - opencl-headers
        - libgl1-mesa-glx
        - libgl1-mesa-dri
        - libgl1-mesa-dev
        - libxcursor-dev
        - libpulse-dev
        - libxinerama-dev
        - libxrandr-dev
        - libxv-dev
        - libasound2-dev
        - libudev-dev
        - mesa-utils
        - mesa-common-dev
        - libglapi-mesa
        - libgbm1
        - libxatracker-dev
#before_install:
#  - sudo add-apt-repository -y ppa:oibaf/graphics-drivers
#  - sudo apt-get update -qq -y
#  - export DEBIAN_FRONTEND=noninteractive
before_script:
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render;
  - sleep 3 
script:
  - glxinfo
  - timeout 5 glxgears || true
