language: python
python: '2.7'
os:
- linux
notifications:
  email: false
dist: xenial
services:
- xvfb
addons:
  apt:
    packages:
    - mesa-utils
    - x11-apps
before_script:
- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile
  --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX
  +render;"
- sleep 3
script:
- timeout 5 glxgears &
- sleep 3
- xwd -name "glxgears" | convert xwd:- "glxgears.png"
deploy:
  provider: releases
  token:
    secure: mdpAlwQPqX37GzOIahyZBH3t8fpWSal+zHUcfTrGBhStVJlhy1eGyz2l0Rl03+48YmFp0kl/gkVPm2Q6inLzUlfKY68jhSrMgvY8qQJCn5Zr2v1np1RoM49XvZcReKG04PxoKXrTTJqhLfMWXgfipRs2nZLULXseL7aYAtV/nrX8FjoiNWV2sQxH170DZ50uK7JusM0/ylwifYq+vm3q+8jgsvBIWYh+1EV+033JyENO1yd3GOaL3fh4wvSQctfu8pdmAofGfNeWBoPcc43VU/uoOKZhRZLTnzZIQneeK+9R/6ryBzdd+3HLEXHmmjeKvImU+hVbdiiW1Pym+tt0h6sbhWIy0vPJiHTkvICQ5ETgLPmcdOgDqYr08/ckNcpZq/MiuuKyOJO1AzGDrjJROioT0NEwXsgCMHD2Aa3r6ifiK61CwmceyeOhKKnVQu5+t2vcSckF0/YFIVBisi39a8VgBUbOPcH9RebGGzunRAox84hcYYZJ6j5SBfIpSt9+5XocnMLRMMWzgNHRVk963zEcSZR2h4pdmORK5IKEeRsEo76GKWR7MmTuPNNdA0dgT8M5zk6b0mwq2bxcyvAf62tAy+vHjvH0kGcO2xyedoQz7TknSFDKW//PCEMcufMVXqZ7/5LnCzWW7F9H6xww67RhAtlidznOFkhYTSK4V+4=
  file: glxgears.png
  on:
    repo: xrombik/dummy_travis_gl
  cleanup: false
